export const FACEBOOK_SIGN_IN_START = 'FACEBOOK_SIGN_IN_START'
export const FACEBOOK_SIGN_IN_SUCCESS = 'FACEBOOK_SIGN_IN_SUCCESS'
export const FACEBOOK_SIGN_IN_FAILURE = 'FACEBOOK_SIGN_IN_FAILURE'

export const EMAIL_SIGN_IN_START = 'EMAIL_SIGN_IN_START'
export const EMAIL_SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS'
export const EMAIL_SIGN_IN_FAILURE = 'SIGN_IN_FAILURE'

export const SIGN_OUT_START = 'SIGN_OUT_START'
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS'
export const SIGN_OUT_FAILURE = 'SIGN_OUT_FAILURE'

export const SIGN_UP_START = 'SIGN_UP_START'
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS'
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE'
